/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
static yyconst short int yy_acclist[98] =
    {   0,
       53,   52,   50,   52,   48,   52,   52,   51,   52,   15,
       52,   52,   13,   52,   16,   52,   17,   52,    9,   52,
        7,   52,   25,   52,    8,   52,   52,   10,   52,    1,
       52,   12,   52,   24,   52,   27,   52,   11,   52,   26,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   20,   52,   21,   52,    4,   52,   18,
       52,   14,   52,   19,   52,   49,   31,    3,   22,    2,
       23,    1,   29,   30,   28,   36,   37,   14,    4,   13,
       15,   38,   44,   39,   40,   42,   34,   45,   32,   33,
       47,   43,   46,   41,   35,    5,    6

    } ;

static yyconst short int yy_accept[141] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    8,   10,   12,
       13,   15,   17,   19,   21,   23,   25,   27,   28,   30,
       32,   34,   36,   38,   40,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   56,   58,
       60,   62,   64,   66,   67,   68,   68,   69,   69,   70,
       71,   72,   72,   73,   74,   75,   76,   76,   76,   76,
       77,   77,   77,   77,   78,   78,   78,   79,   79,   79,
       79,   79,   79,   80,   81,   81,   81,   81,   81,   81,
       81,   81,   82,   82,   82,   82,   82,   82,   82,   82,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       84,   84,   84,   84,   84,   84,   85,   85,   86,   86,
       86,   87,   87,   87,   87,   87,   88,   89,   89,   90,
       91,   91,   91,   92,   92,   92,   93,   94,   94,   94,
       95,   95,   96,   96,   97,   97,   97,   97,   98,   98
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    1,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   40,   32,   41,   42,   32,   32,   32,
       43,    1,   44,    1,   45,    1,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    1,    2,    2,    1,    1,    1
    } ;

static yyconst short int yy_base[141] =
    {   0,
        0,    0,  194,  195,  195,  195,  190,  195,  171,   49,
      195,  195,  195,  195,  195,  195,  175,  173,  175,   84,
      195,  195,  167,  166,  165,  150,  157,   73,   69,  150,
       75,  146,  143,  142,  152,  138,   75,  195,  195,    0,
      195,  195,  195,  195,  195,    0,    0,    0,  195,  160,
      195,  159,   91,  195,  195,  195,  149,  134,  148,  195,
      133,  145,  134,  195,   74,  129,  195,  132,  144,  128,
      134,  133,    0,  195,  121,  121,   84,   86,  138,  129,
      132,  195,  129,  131,  125,  122,  114,  126,  129,  195,
      123,  123,  121,  118,  110,  106,  106,  115,  105,  195,

      107,  114,  113,  112,  100,  195,  112,  195,  105,   97,
      195,   94,  106,  109,  101,  195,  195,   94,  195,  195,
       94,   90,  195,   87,   90,  195,  195,   96,   93,  195,
       98,  195,   82,  195,   96,   84,   93,  195,  195,   50
    } ;

static yyconst short int yy_def[141] =
    {   0,
      139,    1,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  140,
      139,  139,  139,  139,  139,   10,   10,   10,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  140,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,    0,  139
    } ;

static yyconst short int yy_nxt[245] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,    4,   28,   29,   30,    4,    4,
       31,    4,    4,    4,   32,   33,   34,   35,   36,    4,
        4,   37,   38,   39,    4,   40,   41,   42,   43,   46,
       46,   73,   46,   46,   46,   47,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   48,   46,   46,   46,   46,
       46,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   46,   46,   46,   48,   46,   46,   46,   52,   59,

       53,   61,   64,   62,   71,   52,   80,   53,   60,   65,
       90,   92,   72,   81,   91,  138,   93,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,   94,  127,  126,
       95,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   89,   88,   87,   86,   85,   84,   83,   82,   79,
       78,   77,   76,   75,   74,   50,   50,   70,   69,   68,
       67,   66,   63,   58,   57,   56,   55,   54,   51,   50,
       49,   45,   44,  139,    3,  139,  139,  139,  139,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139
    } ;

static yyconst short int yy_chk[245] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   10,
       10,  140,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   20,   28,

       20,   29,   31,   29,   37,   53,   65,   53,   28,   31,
       77,   78,   37,   65,   77,  137,   78,  136,  135,  133,
      131,  129,  128,  125,  124,  122,  121,   78,  118,  115,
       78,  114,  113,  112,  110,  109,  107,  105,  104,  103,
      102,  101,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   89,   88,   87,   86,   85,   84,   83,   81,   80,
       79,   76,   75,   72,   71,   70,   69,   68,   66,   63,
       62,   61,   59,   58,   57,   52,   50,   36,   35,   34,
       33,   32,   30,   27,   26,   25,   24,   23,   19,   18,
       17,    9,    7,    3,  139,  139,  139,  139,  139,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexico.l"
#define INITIAL 0
/* definiciones */
#line 4 "Lexico.l"
	/* includes */

	#include <stdio.h>
	#include <conio.h>
	#include <stdlib.h>
	#include <locale.h>
	#include <string.h>
	#include <float.h>
	#include <limits.h>
	#include "y.tab.h"

	/* defines */

	#define CARACTER_NOMBRE "_"
	#define NO_ENCONTRADO -1
	#define preMaxCadena 46
	#define preMaxEntero 6
	#define TRUE 1
	#define FALSE 0

	/* enums */

	enum valorMaximo{
		ENTERO_MAXIMO = 65535,
		CADENA_MAXIMA = 31,
		TAM = 100
	};

	enum tipoDato{
		tipoInt,
		tipoFloat,
		tipoString,
		sinTipo
	};

	enum sectorTabla{
		sectorVariables,
		sectorConstantes
	};

	enum error{
		errorEnteroFueraDeRango,
		errorRealFueraDeRango,
		errorCadenaDemasiadoLarga,
		errorIdDemasiadoLargo,
		errorCaracterInvalido
	};

	/* structs */

	typedef struct{
		char nombre[100];
		char valor[100];
		enum tipoDato tipo;
		int longitud;
		int limite;
	} registro;

	/* funciones */

	char* cortarCadena(char* ,int);
	char* reemplazarCaracter(char const * const,  char const * const,  char const * const);
	void grabarTablaDeSimbolos(int);
	void insertarEnTablaDeSimbolos(enum sectorTabla,enum tipoDato,char*);
	char* normalizar(char*);
	int buscarEnTablaDeSimbolos(enum sectorTabla, char*);
	void mensajeDeError(enum error,const char*);
	char * cortarCadena(char* ,int);
	void guardarToken(char *);
	char* obtenerTipo(enum sectorTabla, enum tipoDato);
	void mostrarTablaDeSimbolos();

	/* variables globales */

	unsigned long entero64bits;
	registro tablaVariables[TAM];
	registro tablaConstantes[TAM];
	int indiceVariable=0;
	int indiceConstante=0;
	char *tiraDeTokens;
	FILE *yyin;

/* conjuntos y regex */
/* definicion de reglas */
#line 572 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 147 "Lexico.l"


#line 726 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 140 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 195 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 149 "Lexico.l"
{
						guardarToken("CTE_INT");
						strcpy(yylval.cadena, yytext);
						insertarEnTablaDeSimbolos(sectorConstantes, tipoInt, yytext);
						return CTE_INT;
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 156 "Lexico.l"
{
						guardarToken("CTE_FLOAT");
						strcpy(yylval.cadena, yytext);
						insertarEnTablaDeSimbolos(sectorConstantes, tipoFloat, yytext);
						return CTE_FLOAT;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 163 "Lexico.l"
{
						guardarToken("CTE_STRING");
						strcpy(yylval.cadena, yytext);
						printf("valor cadena: %s\n", yylval.cadena);
						insertarEnTablaDeSimbolos(sectorConstantes, tipoString, yytext);
						return CTE_STRING;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 171 "Lexico.l"
{
						guardarToken("ID");
						printf("ID: %s\n",yytext);
						strcpy(yylval.cadena,yytext);
						insertarEnTablaDeSimbolos(sectorVariables, sinTipo, yytext);
						return ID;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 179 "Lexico.l"
{
						guardarToken("INICIO_PROGRAMA");
						return INICIO_PROGRAMA;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 184 "Lexico.l"
{
						guardarToken("FIN_PROGRAMA");
						return FIN_PROGRAMA;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 189 "Lexico.l"
{
						guardarToken("OP_SUM");
						return OP_SUM;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 194 "Lexico.l"
{
						guardarToken("OP_REST");
						return OP_REST;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 199 "Lexico.l"
{	
						guardarToken("OP_MULT");
						return OP_MULT;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 204 "Lexico.l"
{
						guardarToken("OP_DIV");
						return OP_DIV;
					}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 209 "Lexico.l"
{
						guardarToken("OP_ASIG");
						return OP_ASIG;
					}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 214 "Lexico.l"
{
						guardarToken("OP_DEC");
						return OP_DEC;
					}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 219 "Lexico.l"
{
						guardarToken("OP_AND");
						return OP_AND;
					}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 224 "Lexico.l"
{
						guardarToken("OP_OR");
						return OP_OR;
					}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 229 "Lexico.l"
{
						guardarToken("OP_NOT");
						return OP_NOT;
					}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 234 "Lexico.l"
{
						guardarToken("PARENTESIS_I");
						return PARENTESIS_I;
					}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 239 "Lexico.l"
{
						guardarToken("PARENTESIS_F");
						return PARENTESIS_F;
					}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 244 "Lexico.l"
{
						guardarToken("LLAVE_I");
						return LLAVE_I;
					}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 249 "Lexico.l"
{
						guardarToken("LLAVE_F");
						return LLAVE_F;
					}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 254 "Lexico.l"
{
						guardarToken("CORCHETE_I");
						return CORCHETE_I;
					}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 259 "Lexico.l"
{
						guardarToken("CORCHETE_F");
						return CORCHETE_F;
					}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 264 "Lexico.l"
{
						guardarToken("COMENTARIO_I");
						return COMENTARIO_I;
					}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 269 "Lexico.l"
{
						guardarToken("COMENTARIO_F");
						return COMENTARIO_F;
					}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 274 "Lexico.l"
{
						guardarToken("PUNTO_Y_COMA");
						return PUNTO_Y_COMA;
					}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 279 "Lexico.l"
{
						guardarToken("COMA");
						return COMA;
					}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 284 "Lexico.l"
{
						guardarToken("COMP_MAYOR_ESTR");
						strcpy(yylval.cadena, yytext);
						return COMP_MAYOR_ESTR;
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 290 "Lexico.l"
{
						guardarToken("COMP_MENOR_ESTR");
						strcpy(yylval.cadena, yytext);
						return COMP_MENOR_ESTR;
					}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 296 "Lexico.l"
{
						guardarToken("COMP_MAYOR_IGUAL");
						strcpy(yylval.cadena, yytext);
						return COMP_MAYOR_IGUAL;
					}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 302 "Lexico.l"
{
						guardarToken("COMP_MENOR_IGUAL");
						strcpy(yylval.cadena, yytext);
						return COMP_MENOR_IGUAL;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 308 "Lexico.l"
{
						guardarToken("COMP_IGUAL");
						strcpy(yylval.cadena, yytext);
						return COMP_IGUAL;
					}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 314 "Lexico.l"
{
						guardarToken("COMP_DIST");
						strcpy(yylval.cadena, yytext);
						return COMP_DIST;
					}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 320 "Lexico.l"
{
						guardarToken("DECVAR");
						return DECVAR;
					}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 325 "Lexico.l"
{
						guardarToken("ENDDEC");
						return ENDDEC;
					}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 330 "Lexico.l"
{
						guardarToken("WHILE");
						return WHILE;
					}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 335 "Lexico.l"
{
						guardarToken("ENDWHILE");
						return ENDWHILE;
					}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 340 "Lexico.l"
{
						guardarToken("DO");
						return DO;
					}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 345 "Lexico.l"
{
						guardarToken("IF");
						return IF;
					}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 350 "Lexico.l"
{
						guardarToken("ELSE");
						return ELSE;
					}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 355 "Lexico.l"
{
						guardarToken("ELSIF");
						return ELSIF;
					}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 360 "Lexico.l"
{
						guardarToken("ENDIF");
						return ENDIF;
					}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 365 "Lexico.l"
{
						guardarToken("INTEGER");
						return INTEGER;
					}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 370 "Lexico.l"
{
						guardarToken("FLOAT");
						return FLOAT;
					}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 375 "Lexico.l"
{
						guardarToken("STRING");
						return STRING;
					}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 380 "Lexico.l"
{
						guardarToken("READ");
						return READ;
					}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 385 "Lexico.l"
{
						guardarToken("WRITE");
						return WRITE;
					}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 390 "Lexico.l"
{
						guardarToken("BETWEEN");
						return BETWEEN;
					}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 395 "Lexico.l"
{
						guardarToken("INLIST");
						return INLIST;
					}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 399 "Lexico.l"

	YY_BREAK
case 49:
YY_RULE_SETUP
#line 400 "Lexico.l"

	YY_BREAK
case 50:
YY_RULE_SETUP
#line 401 "Lexico.l"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 402 "Lexico.l"

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 403 "Lexico.l"
ECHO;
	YY_BREAK
#line 1234 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 140 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 140 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 139);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 403 "Lexico.l"


/* codigo */

/*
int main(int argc,char *argv[])
{
	setlocale(LC_CTYPE,"Spanish");

	return FALSE;
}
*/

char * reemplazarCaracter(char const * const original,  char const * const pattern,  char const * const replacement)
{
	size_t const replen = strlen(replacement);
	size_t const patlen = strlen(pattern);
	size_t const orilen = strlen(original);
	size_t patcnt = 0;
	const char * oriptr;
	const char * patloc;
	
	for (oriptr = original; patloc = strstr(oriptr, pattern); oriptr = patloc + patlen)
	{
		patcnt++;
	}
	
	size_t const retlen = orilen + patcnt * (replen - patlen);
    char * const returned = (char *) malloc( sizeof(char) * (retlen + 1) );
    
    if (returned != NULL)
    {
		char * retptr = returned;
		
		for (oriptr = original; patloc = strstr(oriptr, pattern); oriptr = patloc + patlen)
		{
			size_t const skplen = patloc - oriptr;
			strncpy(retptr, oriptr, skplen);
			retptr += skplen;
			strncpy(retptr, replacement, replen);
			retptr += replen;
		}
	
		strcpy(retptr, oriptr);
	}
	
	return returned;
}

char * cortarCadena(char* cad,int tam){
	if(strlen(cad)>tam)
	{
		cad[tam]='\0';
	}
	return cad;
}

void grabarTablaDeSimbolos(int error){
	
	setlocale(LC_CTYPE,"Spanish");

	FILE*pt=fopen("tiraDeTokens.txt","w+");
	
	if(!pt)
	{
		printf("Error al crear la tabla de símbolos\n");
		return;
	}
	
	fprintf(pt,"%s",tiraDeTokens);
	fclose(pt);
	
	FILE*pf=fopen("ts.txt","w+");
	int i;
	
	if(!pf){
		printf("Error al crear la tabla de símbolos\n");
		return;
	}
	
	fprintf(pf,"%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13s\n\n","NOMBRE","TIPO","VALOR","LONGITUD","LIMITE");
	
	for(i = 0; i<indiceVariable; i++)
	{
		if(tablaVariables[i].limite!=0)
		{
			fprintf(pf,"%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13d\n",tablaVariables[i].nombre,obtenerTipo(sectorVariables, tablaVariables[i].tipo),"----------------------------","----------",tablaVariables[i].limite);
		}
		else
		{
			fprintf(pf,"%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13s\n",tablaVariables[i].nombre,obtenerTipo(sectorVariables, tablaVariables[i].tipo),"----------------------------","----------","----------");
		}
	}

	for(i = 0; i<indiceConstante; i++)
	{
		if(tablaConstantes[i].longitud==0)
		{
			fprintf(pf,"%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13s\n",tablaConstantes[i].nombre,obtenerTipo(sectorConstantes, tablaConstantes[i].tipo),tablaConstantes[i].valor,"----------","----------");
		}
		else
		{
			fprintf(pf,"%-32s|\t%-15s|\t%-32s|\t%-13d|\t%-13s\n",tablaConstantes[i].nombre,obtenerTipo(sectorConstantes, tablaConstantes[i].tipo),tablaConstantes[i].valor,tablaConstantes[i].longitud,"----------");
		}
	}

	if(error==1) 
	{
		fprintf(pf,"\n**** TABLA INCOMPLETA (ERROR DE COMPILACION) ****\n");
	}
	
	fclose(pf);
}

void mostrarTablaDeSimbolos(){

	setlocale(LC_CTYPE,"Spanish");
	
	printf("%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13s\n\n","NOMBRE","TIPO","VALOR","LONGITUD","LÍMITE");
	int i;
	
	for(i = 0; i<indiceVariable; i++)
	{
		if(tablaVariables[i].limite!=0)
		{
			printf("%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13d\n",tablaVariables[i].nombre,obtenerTipo(sectorVariables, tablaVariables[i].tipo),"----------------------------","----------",tablaVariables[i].limite);
		}
		else
		{
			printf("%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13s\n",tablaVariables[i].nombre,obtenerTipo(sectorVariables, tablaVariables[i].tipo),"----------------------------","----------","----------");
		}
	}

	for(i = 0; i<indiceConstante; i++){
		if(tablaConstantes[i].longitud==0)
		{
			printf("%-32s|\t%-15s|\t%-32s|\t%-13s|\t%-13s\n",tablaConstantes[i].nombre,obtenerTipo(sectorConstantes, tablaConstantes[i].tipo),tablaConstantes[i].valor,"----------","----------");
		}
		else
		{
			printf("%-32s|\t%-15s|\t%-32s|\t%-13d|\t%-13s\n",tablaConstantes[i].nombre,obtenerTipo(sectorConstantes, tablaConstantes[i].tipo),tablaConstantes[i].valor,tablaConstantes[i].longitud,"----------");
		}
	}
}

char* normalizar(char* cadena){
	
	char *aux = (char *) malloc( sizeof(char) * (strlen(cadena)) + 2);
	strcpy(aux,CARACTER_NOMBRE);
	strcat(aux,cadena);
	
	aux=reemplazarCaracter(aux,",","c");
	aux=reemplazarCaracter(aux,".","p");
	aux=reemplazarCaracter(aux,":","d");
	aux=reemplazarCaracter(aux,";","P");
	aux=reemplazarCaracter(aux,"-","m");
	aux=reemplazarCaracter(aux," ","_");
	aux=reemplazarCaracter(aux,"\"","");
	aux=reemplazarCaracter(aux,"[","C");
	aux=reemplazarCaracter(aux,"]","C");
	
	return aux;
}

char* obtenerTipo(enum sectorTabla sector, enum tipoDato tipo){
	switch(sector){
		case sectorConstantes:
			switch(tipo){
				case tipoFloat:
					return("CTE_FLOAT");
					break;
				case tipoString:
					return("CTE_STRING");
					break;
				case tipoInt:
					return("CTE_INT");
					break;
			}
			break;
		case sectorVariables:
			switch(tipo){
				case tipoFloat:
					return("float");
					break;
				case tipoString:
					return("string");
					break;
				case tipoInt:
					return("int");
					break;
				case sinTipo:
					return("sin tipo");
					break;
			}
			break;
	}
}

void insertarEnTablaDeSimbolos(enum sectorTabla sector, enum tipoDato tipo, char *valor){
	
	char *cadena=(char*)malloc(sizeof(char)*CADENA_MAXIMA);
	
	switch(sector){
		case sectorConstantes:
			if(buscarEnTablaDeSimbolos(sectorConstantes,valor)!=NO_ENCONTRADO) {
				return;
			}

			switch (tipo) {
				case tipoFloat:
					if (atof(valor)<0 || atof(valor)>FLT_MAX)
					{
						mensajeDeError(errorRealFueraDeRango,valor);
					}
					strcpy(tablaConstantes[indiceConstante].valor,valor);
					tablaConstantes[indiceConstante].tipo=tipoFloat;
					tablaConstantes[indiceConstante].longitud=0;
					tablaConstantes[indiceConstante].limite=0;
					strcpy(tablaConstantes[indiceConstante++].nombre,normalizar(valor));
					break;

				case tipoString:
					strcpy(cadena,valor);
					cortarCadena(cadena,preMaxCadena);
					cadena=reemplazarCaracter(cadena,"\"","");
					if(strlen(cadena)>=CADENA_MAXIMA)
					{
						mensajeDeError(errorCadenaDemasiadoLarga, cadena);
					}
					strcpy(tablaConstantes[indiceConstante].valor,cadena);
					tablaConstantes[indiceConstante].tipo=tipoString;
					tablaConstantes[indiceConstante].longitud=strlen(cadena);
					tablaConstantes[indiceConstante].limite=0;
					strcpy(tablaConstantes[indiceConstante++].nombre,normalizar(cadena));
					break;

				case tipoInt:
					strcpy(cadena,valor);
					cortarCadena(cadena,preMaxEntero);
					if (atoi(cadena)<0 || atoi(cadena)>ENTERO_MAXIMO)
					{
						mensajeDeError(errorEnteroFueraDeRango,valor);
					}
					strcpy(tablaConstantes[indiceConstante].valor,cadena);
					tablaConstantes[indiceConstante].tipo=tipoInt;
					tablaConstantes[indiceConstante].longitud=0;
					tablaConstantes[indiceConstante].limite=0;
					strcpy(tablaConstantes[indiceConstante++].nombre,normalizar(cadena));
					break;
			}
			break;

		case sectorVariables:
			cadena=cortarCadena(valor,preMaxCadena);
			cadena=reemplazarCaracter(cadena,"\"","");
			if(strlen(cadena)>=CADENA_MAXIMA)
			{
				mensajeDeError(errorCadenaDemasiadoLarga, cadena);
			}
			if(buscarEnTablaDeSimbolos(sectorVariables,cadena)!=NO_ENCONTRADO)
			{
				return;
			}
			strcpy(tablaVariables[indiceVariable].valor,cadena);
			tablaVariables[indiceVariable].tipo=sinTipo;
			tablaVariables[indiceVariable].longitud=0;
			tablaVariables[indiceVariable].limite=0;
			strcpy(tablaVariables[indiceVariable++].nombre,normalizar(cadena));
			break;
	}
}

int buscarEnTablaDeSimbolos(enum sectorTabla sector, char* objetivo){
	
	objetivo=normalizar(objetivo);
	int i;
	
	switch(sector){
		case sectorConstantes:
				for(i=0;i<indiceConstante;i++) 
				{
					if(strcmp(tablaConstantes[i].nombre,objetivo)==0)
					{
						return i;
					}
				}
				return NO_ENCONTRADO;
				break;

		case sectorVariables:
				for(i=0;i<indiceVariable;i++)
				{
					if(strcmp(tablaVariables[i].nombre,objetivo)==0)
					{
						return i;
					}
				}
				return NO_ENCONTRADO;
				break;
	}
	return NO_ENCONTRADO;
}

void mensajeDeError(enum error error,const char* info){

	setlocale(LC_CTYPE,"Spanish");

	grabarTablaDeSimbolos(1);

	printf("[Línea %d] ",yylineno);
	switch(error){ 

        case errorEnteroFueraDeRango: 
            printf("ERROR LÉXICO. Descripción: Int %s fuera de rango [0 ; %d]\n",info,ENTERO_MAXIMO);
            break ;

		case errorRealFueraDeRango: 
            printf("ERROR LÉXICO. Descripción: Float %s fuera de rango. Debe ser un float de 32bits.\n",info);
            break ;

        case errorCadenaDemasiadoLarga:
            printf("ERROR LÉXICO. Descripción: String \"%s\" fuera de rango. La longitud máxima es de 30 caracteres.\n", info);
            break ; 

        case errorIdDemasiadoLargo:
            printf("ERROR LÉXICO. Descripción: Id \"%s\" demasiado largo. La longitud máxima es de 30 caracteres.\n", info);
            break ; 

        case errorCaracterInvalido:
        	printf("ERROR LÉXICO. Descripción: El caracter %s es inválido.\n",info);
        	break;
    }
       
    system ("Pause");
	exit (1);
}

void guardarToken(char* token){
	char* aux = (char*) malloc ( sizeof(char) * (strlen(tiraDeTokens)) +1);
	strcpy(aux, tiraDeTokens);
	tiraDeTokens=(char*) malloc ( sizeof(char) * (strlen(aux)) + strlen(token)+1);
	strcpy(tiraDeTokens,aux);
	strcat(tiraDeTokens,token);
}